### PR TITLE
Merge to staging - pull request

### PR DESCRIPTION
**Pull request by m-stein**
This is an update to the most recent stable state of @cnuke and me.

### CODE REVIEW

**Comment by m-stein** [comment]
I think it would be sensible to incorporate fix-up commits in the history directly after their original commits. This is why I'd suggest to add such commits on my merge_to_staging branch and leave the merge_to_staging_pull_request as it is (as a force push is bad for pull requests).

**Comment by jklmnn** [comment]
It seems I forgot to remove your fixup commit from the middle of my branch. I can remove it from my PR so we can merge it with yours. Although I'd prefer to keep the current order of pull requests.

**Comment by m-stein** [comment]
I cannot inspect the fix-up in your PR, thus, I'd prefer to keep my version.

**Comment by m-stein** [comment]
I'd suggest to squash all review commits from the last successful PR of @cnuke together to one commit and then squash in also https://github.com/cbe-project/cbe/pull/41/commits/2dd4f04e26f0f4ba8e78d7d969bb1470fb280d45 of this PR.

**Comment by jklmnn** [comment]
> I cannot inspect the fix-up in your PR, thus, I'd prefer to keep my version.

I already removed this commit from my PR.

> I'd suggest to squash all review commits from the last successful PR of @cnuke together to one commit and then squash in also [2dd4f04](https://github.com/cbe-project/cbe/commit/2dd4f04e26f0f4ba8e78d7d969bb1470fb280d45) of this PR.

I squashed the commits you mentioned together.

**Comment by m-stein** [comment]
@jklmnn I wonder why this PR doesn't apply anymore? Also, is there a way of merging with my own tooling (git rebase/cherry-pick, git mergetool) instead of the github GUI without irritating the PR on github?

**Comment by senier** [comment]
The reason is that @jklmnn integrated your commits into staging as discussed above. This changed the history of the staging branch which is the reason that you current PR does not apply anymore. To resolve this, fetch the upstream staging branch (on the command line) and rebase your `merge_to_staging_pull_request` onto it. Then, you can (force) push it again and changes should appear in this PR then.

**Comment by m-stein** [comment]
Thanks for the hint. I thought he'd squash my fix-up only after the PR was approved and I also thought that force pushing PR branches should be avoided.

**Comment by senier** [comment]
>  and I also thought that force pushing PR branches should be avoided.

How would you address changes the reviewers requested then? We force push to PR branches all the time without issues - GitHub will update the PR view highlighting changes since you last review.

**Comment by m-stein** [comment]
Please keep in mind that I'm not experienced with this workflow, I just read it in the Github PR doc:

_"When pushing commits to a pull request, don't force push. Force pushing can corrupt your pull request."_

**Comment by m-stein** [comment]
@senier @jklmnn We're looking forward to add further pull requests. So, if you currently don't have the time to review this one, would you be fine with @cnuke attending to the matter?

**Review by jklmnn — APPROVED** [review]

**Comment by jklmnn** [comment]
Sorry, GitHub didn't deliver a notification that you changed the pull request. I reviewed it and it looks good to me.

**Comment by m-stein** [comment]
@jklmnn No problem, I've rebased the new cbe-project/staging to change the commit message of "fixup "review lib/cbe: *" (prove with mode flow)" to something sensible. The result is my cbe_project_staging_rebased branch which I would suggest as new staging.

**Comment by senier** [comment]
@jklmnn @m-stein @cnuke GitHub does not seem to emit notification if a PR is updated (probably because that would cause many mails if you do this incrementally). Hence, we should notify the original reviewers when there is a new state on a PR worth reviewing. This can be done by pressing the [rerequest review](https://github.blog/changelog/2019-02-21-re-request-review-on-a-pull-request/) button next to the reviewer.

**Pull request merged**
