### PR TITLE
Staging

### PR DESCRIPTION
**Pull request by cnuke**

### CODE REVIEW

**Review by jklmnn — CHANGES_REQUESTED** [review]
@cnuke can you please check the comments in #34 since this pull request contains the same commits (and it wouldn't make sense to review the same code for the same comments again).

**Comment by cnuke** [comment]
@jklmnn sure. Thanks for the review, I've pushed a [branch](https://github.com/cnuke/cbe/commits/jklmnn_review) with the commits addressing the remarks which could become the next staging branch.

**Comment by jklmnn** [comment]
@cnuke can you please add the comments to this branch (w/o force pushing/deleting it)? Otherwise I can't merge these changes. Also GitHub will mark what has changed since the last review so I can easily see it.

**Comment by cnuke** [comment]
@jklmnn sure thing - there you go.

**Review by jklmnn — APPROVED** [review]
The comments of #34 are fixed in https://github.com/cbe-project/cbe/pull/37/commits/bb18b5dad3d7a27c0862d3bd5cde232a249ff7e6 .. https://github.com/cbe-project/cbe/pull/37/commits/3dba3166a3e5cfc0e195fb084b95eef0c6e19cd9. See the comments there for more details.

**Pull request merged**
